version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: ${DOCKER_CONTAINER_NAME}
    restart: always
    ports:
      - "8000:8000"
      - "${PORTAINER_PORT}:${PORTAINER_PORT}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: